# Service Configuration
services:
  redis:
    host: localhost
    port: 6379
    db: 0
  
  voice_platforms:
    vapi:
      webhook_url: "/webhook/voice"
    retell:
      webhook_url: "/webhook/retell"

# LLM Configuration  
llm:
  provider: openai
  model: gpt-4
  temperature: 0.1
  max_tokens: 1000

# Tool Configuration
tools:
  enabled: ["menu", "sheets"]
  timeout: 30
